//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcentratorDetail
    {
        public int ID { get; set; }
        public Nullable<int> CellID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public string InstallPerson { get; set; }
        public System.Data.Spatial.DbGeography Coordinates { get; set; }
        public Nullable<int> ClientDetailsID { get; set; }
    
        public virtual ClientDetail ClientDetail { get; set; }
    }
}
