//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterDetail
    {
        public int ID { get; set; }
        public string AccountNumber { get; set; }
        public string MeterType { get; set; }
        public Nullable<int> MeterCount { get; set; }
        public int UnitID { get; set; }
        public Nullable<System.DateTime> LastReadingDate { get; set; }
        public string LastMeterReading { get; set; }
        public string StreetAddress { get; set; }
        public string Suburb { get; set; }
        public string Town { get; set; }
        public string PhysicalMeterNumber { get; set; }
        public string ConsumerName { get; set; }
        public string ErfNumber { get; set; }
        public string MeterLocation { get; set; }
        public string AvgReading { get; set; }
        public Nullable<int> isSingleorDuelFlow { get; set; }
        public Nullable<bool> isBulkMeter { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public string InstallPerson { get; set; }
        public System.Data.Spatial.DbGeography Coordinates { get; set; }
        public Nullable<int> ClientDetailsID { get; set; }
        public Nullable<int> DialCount { get; set; }
        public Nullable<int> ProductType { get; set; }
        public string Route { get; set; }
        public string ReadingPoint { get; set; }
        public Nullable<int> Allocation { get; set; }
    
        public virtual ClientDetail ClientDetail { get; set; }
    }
}
