//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReading
    {
        public int ID { get; set; }
        public System.DateTime TSDateTime { get; set; }
        public System.DateTime TSInsertedDate { get; set; }
        public Nullable<long> UnitID { get; set; }
        public int CellID { get; set; }
        public Nullable<int> VBAT { get; set; }
        public Nullable<int> RSSI { get; set; }
        public Nullable<int> Conf { get; set; }
        public Nullable<int> FW { get; set; }
        public Nullable<int> WACC { get; set; }
        public Nullable<int> ProductType { get; set; }
        public Nullable<int> AreaCode { get; set; }
        public Nullable<int> EndOfMonth { get; set; }
        public Nullable<int> EndOfMonthDay { get; set; }
        public Nullable<int> MeterTotalToDate { get; set; }
        public string WMDOverrideStatus { get; set; }
        public string WMDTamperStatus { get; set; }
        public string WMDValveState { get; set; }
        public string WMDValveFault { get; set; }
        public string WMDLeakStatus { get; set; }
    }
}
