//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SebataAMREntities : DbContext
    {
        public SebataAMREntities()
            : base("name=SebataAMREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClientDetail> ClientDetails { get; set; }
        public DbSet<ConcentratorDetail> ConcentratorDetails { get; set; }
        public DbSet<MeterDetail> MeterDetails { get; set; }
        public DbSet<MeterReading> MeterReadings { get; set; }
    }
}
